(() => {
"use strict";
const DB = window.WUS_CARD_DATABASE || [];
const byId = Object.fromEntries(DB.map(card => [card.id, card]));
const DECKS_KEY = "wus-saved-decks-v1";
const ACTIVE_KEY = "wus-active-deck-v1";
let deck = {};
let activeDeckId = null;
let selectedCard = null;
let selectedForm = 0;
const $ = id => document.getElementById(id);
const els = Object.fromEntries(["deckName","newDeckBtn","saveDeckBtn","savedDecks","deleteDeckBtn","goldBalance","previewImage","formTabs","previewName","previewOwned","previewMeta","previewStats","previewCharacteristics","previewEffect","previewEffectName","deckSummary","deckStatus","deckList","emptyDeck","clearDeckBtn","searchCards","typeFilter","rarityFilter","costMin","costMax","atkMin","hpMin","rangeMin","spdMin","ownedOnly","resetFilters","cardBrowser","emptyBrowser","visibleCount"].map(id=>[id,$(id)]));
const slug=s=>String(s).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const owned=id=>window.WUSCollection?.getOwned(id)||0;
const sharedQty=gameplayId=>Object.entries(deck).reduce((n,[id,q])=>n+(byId[id]?.gameplayId===gameplayId?q:0),0);
const printingQty=id=>deck[id]||0;
function canAdd(card){return owned(card.id)>printingQty(card.id)&&sharedQty(card.gameplayId)<card.copyLimit;}
function loadDecks(){try{return JSON.parse(localStorage.getItem(DECKS_KEY))||{};}catch{return {};}}
function storeDecks(v){localStorage.setItem(DECKS_KEY,JSON.stringify(v));}
function saveActive(){localStorage.setItem(ACTIVE_KEY,JSON.stringify({name:els.deckName.value,deck}));}
function populateFilters(){[...new Set(DB.flatMap(c=>c.types))].sort().forEach(v=>els.typeFilter.add(new Option(v,v)));["Common","Uncommon","Rare","Super Rare","Ultra Rare","Secret Rare"].forEach(v=>els.rarityFilter.add(new Option(v,v)));}
function populateSaved(){const decks=loadDecks();els.savedDecks.innerHTML='<option value="">Load saved deck…</option>';Object.entries(decks).sort((a,b)=>b[1].updated-a[1].updated).forEach(([id,d])=>els.savedDecks.add(new Option(d.name,id)));els.savedDecks.value=activeDeckId||"";els.deleteDeckBtn.disabled=!activeDeckId;}
async function setImg(img,path){img.src="card-back.png";try{img.src=window.WUSAssets?await WUSAssets.getObjectUrl(path):encodeURI(path);}catch{img.src=encodeURI(path);}}
function formData(card){return card.forms?.[selectedForm]||card;}
function selectCard(card){selectedCard=card;selectedForm=0;renderPreview();document.querySelectorAll('.browser-card').forEach(e=>e.classList.toggle('selected',e.dataset.id===card.id));}
function renderPreview(){const c=selectedCard;if(!c)return;const f=formData(c);setImg(els.previewImage,c.image);els.previewName.textContent=f.name||c.name;els.previewOwned.textContent=`Owned ${owned(c.id)} / ${c.copyLimit}`;els.previewMeta.textContent=`${c.id} · ${c.rarity} · ${c.types.join(" / ")}${c.isSecret?" · Secret printing":""}`;els.previewStats.innerHTML=[["COST",f.cost],["ATK",f.atk],["HP",f.hp],["RNG",f.range],["SPD",f.spd]].map(([k,v])=>v===null||v===undefined?'':`<div class="stat"><small>${k}</small><strong>${v}</strong></div>`).join('');els.previewCharacteristics.innerHTML=(f.characteristics||[]).map(x=>`<span class="tag">${x}</span>`).join('');els.previewEffect.hidden=!f.effectName;els.previewEffectName.textContent=f.effectName||'';if(c.forms){els.formTabs.hidden=false;els.formTabs.innerHTML=c.forms.map((x,i)=>`<button class="form-tab ${i===selectedForm?'active':''}" data-form="${i}">${x.name}</button>`).join('');els.formTabs.querySelectorAll('button').forEach(b=>b.onclick=()=>{selectedForm=Number(b.dataset.form);renderPreview();});}else{els.formTabs.hidden=true;els.formTabs.innerHTML='';}}
function addCard(id){const c=byId[id];if(!c||!canAdd(c))return;deck[id]=(deck[id]||0)+1;saveActive();renderDeck();renderBrowser();}
function removeCard(id){if(!deck[id])return;deck[id]-=1;if(deck[id]<=0)delete deck[id];saveActive();renderDeck();renderBrowser();}
function renderDeck(){const entries=Object.entries(deck).filter(([,q])=>q>0).sort(([a],[b])=>byId[a].name.localeCompare(byId[b].name));const total=entries.reduce((n,[,q])=>n+q,0);els.deckSummary.textContent=`${total} total cards · ${entries.length} unique`;els.emptyDeck.hidden=entries.length>0;els.deckList.innerHTML='';let violations=[];const groupTotals={};entries.forEach(([id,q])=>{const c=byId[id];groupTotals[c.gameplayId]=(groupTotals[c.gameplayId]||0)+q;if(q>owned(id))violations.push(`${c.name}: deck uses ${q}, owned ${owned(id)}`);});Object.entries(groupTotals).forEach(([gid,q])=>{const c=DB.find(x=>x.gameplayId===gid);if(q>c.copyLimit)violations.push(`${c.name}: ${q}/${c.copyLimit} shared copies`);});els.deckStatus.className=`deck-status ${violations.length?'invalid':'valid'}`;els.deckStatus.textContent=violations.length?violations.join(' · '):'No ownership or copy-limit violations.';
entries.forEach(([id,q])=>{const c=byId[id];const div=document.createElement('article');div.className=`deck-entry ${c.isSecret?'secret':''}`;div.innerHTML=`<img class="deck-thumb" src="card-back.png" alt=""><div class="deck-card-info"><strong>${c.name}</strong><small>${c.id} · ${c.rarity}</small><small>Owned ${owned(id)} · Shared ${sharedQty(c.gameplayId)}/${c.copyLimit}</small></div><div class="qty-controls"><button class="qty-btn minus" aria-label="Remove one">−</button><span class="qty">${q}</span><button class="qty-btn plus" aria-label="Add one" ${canAdd(c)?'':'disabled'}>+</button></div>`;setImg(div.querySelector('img'),c.image);div.onmouseenter=()=>selectCard(c);div.querySelector('.minus').onclick=e=>{e.stopPropagation();removeCard(id)};div.querySelector('.plus').onclick=e=>{e.stopPropagation();addCard(id)};els.deckList.append(div);});
const counts={Character:0,Animal:0,Action:0,Item:0,Construct:0,Army:0,Event:0,Stronghold:0};entries.forEach(([id,q])=>byId[id].types.forEach(t=>{if(t in counts)counts[t]+=q;}));Object.entries(counts).forEach(([t,n])=>{const e=$("count"+t);if(e)e.textContent=n;});}
function matches(c){const q=els.searchCards.value.trim().toLowerCase();const have=owned(c.id);if(c.isSecret&&!have)return false;if(els.ownedOnly.checked&&!have)return false;if(els.typeFilter.value!=='All'&&!c.types.includes(els.typeFilter.value))return false;if(els.rarityFilter.value!=='All'&&c.rarity!==els.rarityFilter.value)return false;const nums=[['costMin','cost',v=>v>=Number(els.costMin.value)],['costMax','cost',v=>v<=Number(els.costMax.value)],['atkMin','atk',v=>v>=Number(els.atkMin.value)],['hpMin','hp',v=>v>=Number(els.hpMin.value)],['rangeMin','range',v=>v>=Number(els.rangeMin.value)],['spdMin','spd',v=>v>=Number(els.spdMin.value)]];for(const [eid,key,test] of nums){if(els[eid].value!==''&&!test(c[key]??-Infinity))return false;}if(!q)return true;const hay=[c.id,c.name,c.rarity,c.effectName,...c.types,...c.characteristics,...(c.forms||[]).flatMap(f=>[f.name,f.effectName,...f.characteristics])].join(' ').toLowerCase();return hay.includes(q);}
function renderBrowser(){const list=DB.filter(matches);els.visibleCount.textContent=`${list.length} shown`;els.emptyBrowser.hidden=list.length>0;els.cardBrowser.innerHTML='';list.forEach(c=>{const have=owned(c.id), used=printingQty(c.id);const div=document.createElement('article');div.className=`browser-card ${have?'':'unowned'} ${c.isSecret?'secret':''}`;div.dataset.id=c.id;div.innerHTML=`<img class="browser-thumb" src="card-back.png" alt=""><div class="browser-info"><strong>${c.name}</strong><small>${c.id}</small><small class="rarity-${slug(c.rarity)}">${c.rarity}</small><small class="owned-count">Owned ${have} · Deck ${used}</small></div><button class="browser-add" aria-label="Add ${c.name}" ${canAdd(c)?'':'disabled'}>+</button>`;setImg(div.querySelector('img'),c.image);div.onclick=()=>selectCard(c);div.ondblclick=()=>addCard(c.id);div.onmouseenter=()=>selectCard(c);div.querySelector('button').onclick=e=>{e.stopPropagation();addCard(c.id)};els.cardBrowser.append(div);});if(selectedCard)document.querySelector(`[data-id="${selectedCard.id}"]`)?.classList.add('selected');}
function resetFilters(){['searchCards','costMin','costMax','atkMin','hpMin','rangeMin','spdMin'].forEach(id=>els[id].value='');els.typeFilter.value='All';els.rarityFilter.value='All';els.ownedOnly.checked=false;renderBrowser();}
function newDeck(){deck={};activeDeckId=null;els.deckName.value='New Deck';saveActive();populateSaved();renderDeck();renderBrowser();}
els.newDeckBtn.onclick=newDeck;els.clearDeckBtn.onclick=()=>{if(confirm('Remove every card from this deck?')){deck={};saveActive();renderDeck();renderBrowser();}};els.saveDeckBtn.onclick=()=>{const decks=loadDecks();const id=activeDeckId||`deck-${Date.now()}`;decks[id]={name:els.deckName.value.trim()||'Untitled Deck',cards:{...deck},updated:Date.now()};storeDecks(decks);activeDeckId=id;populateSaved();};els.savedDecks.onchange=()=>{const id=els.savedDecks.value;if(!id)return;const d=loadDecks()[id];if(!d)return;activeDeckId=id;deck={...d.cards};els.deckName.value=d.name;saveActive();populateSaved();renderDeck();renderBrowser();};els.deleteDeckBtn.onclick=()=>{if(!activeDeckId||!confirm('Delete this saved deck?'))return;const decks=loadDecks();delete decks[activeDeckId];storeDecks(decks);newDeck();};['searchCards','typeFilter','rarityFilter','costMin','costMax','atkMin','hpMin','rangeMin','spdMin','ownedOnly'].forEach(id=>els[id].addEventListener(id==='searchCards'?'input':'change',renderBrowser));['costMin','costMax','atkMin','hpMin','rangeMin','spdMin'].forEach(id=>els[id].addEventListener('input',renderBrowser));els.resetFilters.onclick=resetFilters;window.addEventListener('wus-player-data-changed',()=>{els.goldBalance.textContent=`${WUSCollection.load().gold.toLocaleString()} Gold`;renderDeck();renderBrowser();renderPreview();});
function init(){populateFilters();populateSaved();try{const active=JSON.parse(localStorage.getItem(ACTIVE_KEY));if(active){deck=active.deck||{};els.deckName.value=active.name||'New Deck';}}catch{}els.goldBalance.textContent=`${(WUSCollection?.load().gold||0).toLocaleString()} Gold`;renderDeck();renderBrowser();if(DB.length)selectCard(DB.find(c=>owned(c.id)>0&&!c.isSecret)||DB[0]);}
init();
})();